### ISSUE TITLE
你好，有个问题，关于pod的

### ISSUE THREAD

**Issue by RenmuNyan** [SamuelYu233/iOSdev#1]
我也是根据某个教程学习这个项目的开发，但是在pod框架的时候遇到了问题。
提到的4个框架3个出现了问题，比较明显的是UIColor+KVNContrast.h
我并不清楚是原库的问题还是我的问题，所以我git了您的项目，发现并没有以上所有问题
所以想请教一下，您是否有做什么处理。

Xcode 7.2 用swift2.0

**Comment by FunkySamuel37** [comment]
这个视频用到的几个框架比较坑，有一些干脆就不更新了，试试看github上面怎么说吧。一般作者会在readme里面写怎么引入最新版本的，要是太老还不更新的干脆就换一个用吧。
如果是oc的框架就没问题了，还有报错可能是因为要配置arc什么的吧。（记不清了，好像pod引入的不用配置arc）
我是麦子学院其中一期学员，到现在都没找到工作呢😂，现在在学web方面的东西，ios好久不碰了

**Comment by RenmuNyan** [comment]
主要报错的比较奇怪，几乎用到UIKit的方法或类都报错，而且我都是获取pod上面最新的框架。我也是看到视频感觉挺好玩的然后就……项目开始就卡住了，我也是第一次用到swift项目然后去pod OC的框架，然后错了好慌。行咯行咯谢谢啦~
